name: Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet dependencies
        run: nuget restore

      - name: Download .NET 8 Desktop Runtime
        run: curl -L -o Installer\Bundle\windowsdesktop-runtime-8.0.15-win-x64.exe https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/8.0.15/windowsdesktop-runtime-8.0.15-win-x64.exe

      - name: Build all
        run: MSBuild $Env:GITHUB_WORKSPACE /p:Configuration=Release /p:SignAssembly=false

  build-arm64:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet dependencies
        run: nuget restore

      - name: Build all
        run: MSBuild $Env:GITHUB_WORKSPACE /p:Configuration=Release /p:Platform=ARM64 /p:SignAssembly=false