name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-release-x64:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet dependencies
        run: nuget restore

      - name: Build all
        run: MSBuild $Env:GITHUB_WORKSPACE /p:Configuration=Release /p:SignAssembly=false

      - name: Rename installer bundle
        shell: bash
        run: mv Installer/Bundle/bin/Release/Bundle.exe EverythingToolbar-${{ github.ref_name }}.exe

  build-release-arm64:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet dependencies
        run: nuget restore

      - name: Build all
        run: MSBuild $Env:GITHUB_WORKSPACE /p:Configuration=Release /p:Platform=ARM64 /p:SignAssembly=false

      - name: Rename installer bundle
        shell: bash
        run: mv Installer/Bundle/bin/ARM64/Release/Bundle.exe EverythingToolbar-${{ github.ref_name }}-arm64.exe

  release:
    needs: [build-release-x64, build-release-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            "EverythingToolbar-${{ github.ref_name }}.exe" \
            "EverythingToolbar-${{ github.ref_name }}-arm64.exe" \
            "EverythingToolbar-${{ github.ref_name }}.sha256" \
            --draft \
            --title "${{ github.ref_name }}"